apiVersion: v1
kind: Namespace
metadata:
  name: auditlog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: auditlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook
        image: quay.io/tavaresrodrigo/mywebhook
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: auditlog
spec:
  selector:
    app: webhook
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook
  namespace: auditlog
spec:
  host: mywebhook.apps.audit.sandbox210.opentlc.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: webhook
